import assert from 'node:assert/strict';
import {trustedClassroomOrigin,initClassroomBridge} from '../js/blocks/classroom-bridge.js';
assert.ok(trustedClassroomOrigin('https://abc-script.googleusercontent.com'));
for(const origin of ['null','http://abc-script.googleusercontent.com','https://evil.com','https://abc-script.googleusercontent.com.evil.com']) assert.equal(trustedClassroomOrigin(origin),false);
let listener,replies=[];const parent={postMessage:(data,origin)=>replies.push({data,origin})};
globalThis.location={search:'?classroom=1'};globalThis.window={parent,addEventListener:(_,fn)=>listener=fn};
let click;const button={addEventListener:(_,fn)=>click=fn};
globalThis.document={createElement:()=>button,querySelector:()=>({insertBefore:()=>{},querySelector:()=>null})};
let snapshot={kind:'blocks',v:1,comps:[],params:{L:100}};
initClassroomBridge(()=>snapshot,'test');
assert.equal(replies.pop().data.type,'cadcam:ready');
const event={source:parent,origin:'https://abc-script.googleusercontent.com',data:{type:'cadcam:snapshot-request',id:'12345678-1234-1234-1234-123456789abc'}};
listener({...event,source:{}});listener({...event,origin:'https://evil.com'});assert.equal(replies.length,0);
listener(event);snapshot.params.L=200;assert.equal(JSON.parse(replies[0].data.snapshot).params.L,100);assert.equal(replies[0].origin,event.origin);
listener({...event,data:{type:'cadcam:report-state',enabled:true}});
assert.equal(button.disabled,false);click();assert.equal(button.disabled,true);
assert.equal(replies.at(-1).data.type,'cadcam:report-open');assert.equal(replies.at(-1).origin,event.origin);
listener({...event,origin:'https://evil.com',data:{type:'cadcam:report-state',enabled:true}});assert.equal(button.disabled,true);
console.log('classroom-bridge: source, origin, request and frozen snapshot verified');
