import { prepareParallelLiftOperation as prepare, createParallelLiftOperationSession } from '../js/blocks/parallel-lift-operations.js';
import { planParallelLift } from '../js/blocks/parallel-lift-workflow.js';
import { getExample } from '../js/blocks/examples.js';
import { normalizeSnapshot, toSnapshot } from '../js/blocks/schema.js';
import { encodeSnapshot, decodeShareString } from '../js/share-codec.js';
import { validateMotionRange } from '../js/blocks/motion-range-validation.js';
import { check, report } from './_harness.mjs';
const clone=v=>JSON.parse(JSON.stringify(v)), source=clone(getExample('parallel-fourbar').snapshot), original=JSON.stringify(source);
const req=(parameters,action='createFromExample')=>({operationVersion:1,action,...(action==='createFromExample'?{exampleId:'parallel-fourbar'}:{}),parameters});
const create=p=>prepare(null,req(p));
check('預設既有範例五件與姿態採樣通過',create().ok && create().candidateSnapshot.comps.length===5 && create().validation.scope.sampleChecks===2);
for(const arm of [32,48,64,120]){const r=create({armLengthMm:arm,startHeightMm:0,endHeightMm:arm*.8});check(`同步兩臂${arm}與高度求角`,r.ok&&r.candidateSnapshot.params.LL1===arm&&r.candidateSnapshot.params.LL2===arm&&Math.abs(r.plan.end.height-arm*.8)<1e-5);}
check('高度過教學分支明拒',create({endHeightMm:120}).issues[0].code==='UNREACHABLE_HEIGHT'&&!create({endHeightMm:120}).candidateSnapshot);
for(const p of [{armLengthMm:'64'},{armLengthMm:31},{armLengthMm:121},{endHeightMm:NaN},{endHeightMm:Infinity},{other:1},null])check('未知欄位或非法輸入拒絕',!create(p).ok);
for(const r of [{operationVersion:2,action:'updateTask'}, {...req({}),exampleId:'competition-lift'}, {...req({}),unknown:1}])check('非法請求拒絕',!prepare(source,r).ok);
const uneven=clone(source);uneven.params.LL2=56;
check('破壞等長明確診斷',prepare(uneven,req({},'updateTask')).issues[0].code==='EQUAL_ARMS_REQUIRED');
check('明確同步臂長可修正等長錯誤',prepare(uneven,req({armLengthMm:64},'updateTask')).ok);
const phase=clone(source);phase.comps[2].phaseOffset=5;check('非原分支零相位拒絕',prepare(phase,req({},'updateTask')).issues[0].code==='UNSUPPORTED_STRUCTURE');
check('逆向與同高都可驗證',create({startHeightMm:35,endHeightMm:10}).ok&&create({startHeightMm:10,endHeightMm:10}).validation.sampleCount===1);
const corrected=create({armLengthMm:64,endHeightMm:45});check('錯誤修正後重驗有效',corrected.ok);
check('來源不被修改',JSON.stringify(source)===original);
const share=decodeShareString(encodeSnapshot(corrected.candidateSnapshot));check('分享重開相同任務plan',prepare(share,req({},'updateTask')).ok&&prepare(share,req({},'updateTask')).plan.endHeightMm===45&&share.params.LL1===64);
const norm=normalizeSnapshot(corrected.candidateSnapshot),saved=toSnapshot(norm.comps,{params:norm.params,tracePoints:['C']},norm.counter);check('JSON保存重開參數與主孔保留',prepare(saved,req({},'updateTask')).ok&&saved.params.parallelEndHeight===45&&saved.tracePoint==='C');
let current=clone(source),undo=[];const session=createParallelLiftOperationSession({getSnapshot:()=>current,applySnapshot:s=>{undo.push(clone(current));current=s;}});
session.prepare(req({armLengthMm:64,endHeightMm:45},'updateTask'));check('預覽零作品副作用',JSON.stringify(current)===original&&undo.length===0);
check('兩臂和任務批次一筆undo',session.confirm().applied&&undo.length===1&&current.params.LL1===64&&current.params.LL2===64);
check('消費後不能重複確認',session.confirm().issues[0].code==='STALE_SOURCE');current=undo.pop();check('完整undo回原作品',JSON.stringify(current)===original);
session.prepare(req({},'updateTask'));check('同值不新增undo',!session.confirm().applied&&undo.length===0);
session.prepare(req({armLengthMm:64},'updateTask'));session.cancel();check('取消不改來源',!session.confirm().ok&&JSON.stringify(current)===original);
session.prepare(req({armLengthMm:64},'updateTask'));current.params.LL2=56;check('過期候選拒絕保留新作品',session.confirm().issues[0].code==='STALE_SOURCE'&&current.params.LL2===56);
const sampleFail=validateMotionRange(source,{startDeg:10,endDeg:20,sampleChecks:[{code:'ATTITUDE_NOT_PRESERVED',componentId:'Link3',targets:['C','D'],test:(_p,a)=>a<15}]});check('逐樣本可信檢查失敗含角與零件',sampleFail.issues.some(i=>i.code==='ATTITUDE_NOT_PRESERVED'&&i.angleDeg===15&&i.componentId==='Link3'));
for(const bad of [{...source,comps:[null]},{...source,comps:source.comps.map(c=>({...c,p1:null}))},{...source,params:{...source.params,LL3:NaN}}])check('公開planner非法來源明拒不throw',!planParallelLift(bad).ok);
report('parallel-lift');
